<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RecipeManager.Domain\RecipeManager.Domain.csproj" />
    <ProjectReference Include="..\RecipeManager.Infrastructure\RecipeManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\Favorites\" />
    <Folder Include="Contracts\Ingredients\" />
    <Folder Include="Contracts\Recipes\" />
    <Folder Include="Contracts\Users\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
