-- Recipe Manager — PostgreSQL schema
-- Regenerated to match the current EF Core migrations:
--   20260805135746_InitialCreate
--   20260806104603_AddLoginTokens
--   20260810120655_FixPendingModelChanges
--   20260813075849_WidenIngredientAmount
--   20260821155107_AddRecipeImageUrl
-- If you change the EF model, regenerate instead of editing by hand:
--   dotnet ef migrations script --idempotent --project RecipeManager.Infrastructure --startup-project RecipeManager.Api

-- Table: categories
CREATE TABLE categories (
    category_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT PK_categories PRIMARY KEY (category_id)
);

-- Table: cuisines
CREATE TABLE cuisines (
    cuisine_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT PK_cuisines PRIMARY KEY (cuisine_id)
);

-- Table: ingredients
CREATE TABLE ingredients (
    ingredient_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT PK_ingredients PRIMARY KEY (ingredient_id)
);

-- Table: roles
CREATE TABLE roles (
    role_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT PK_roles PRIMARY KEY (role_id)
);

-- Table: users
CREATE TABLE users (
    user_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    email varchar(255) NOT NULL,
    phone varchar(20) NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_users PRIMARY KEY (user_id)
);

-- Table: login_tokens
CREATE TABLE login_tokens (
    login_token_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id int NOT NULL,
    code_hash varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL,
    used_at timestamptz NULL,
    CONSTRAINT PK_login_tokens PRIMARY KEY (login_token_id)
);

-- Table: recipes
CREATE TABLE recipes (
    recipe_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    author_id int NOT NULL,
    cuisine_id int NOT NULL,
    category_id int NOT NULL,
    title varchar(100) NOT NULL,
    prep_time_minutes int NOT NULL,
    cook_time_minutes int NOT NULL,
    servings int NOT NULL,
    instructions text NULL,
    image_url varchar(2048) NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_recipes PRIMARY KEY (recipe_id),
    CONSTRAINT CK_recipes_servings CHECK (servings > 0),
    CONSTRAINT CK_recipes_prep_time CHECK (prep_time_minutes > 0),
    CONSTRAINT CK_recipes_cook_time CHECK (cook_time_minutes > 0)
);

-- Table: users_roles (many-to-many user ↔ role)
CREATE TABLE users_roles (
    user_id int NOT NULL,
    role_id int NOT NULL,
    CONSTRAINT PK_users_roles PRIMARY KEY (user_id, role_id)
);

-- Table: user_favorites (many-to-many user ↔ recipe)
CREATE TABLE user_favorites (
    user_id int NOT NULL,
    recipe_id int NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_user_favorites PRIMARY KEY (user_id, recipe_id)
);

-- Table: recipe_ingredients (many-to-many recipe ↔ ingredient)
CREATE TABLE recipe_ingredients (
    recipe_id int NOT NULL,
    ingredient_id int NOT NULL,
    amount numeric(10,2) NOT NULL,
    unit varchar(10) NOT NULL,
    CONSTRAINT PK_recipe_ingredients PRIMARY KEY (recipe_id, ingredient_id),
    CONSTRAINT CK_recipe_ingredients_amount CHECK (amount > 0)
);

-- Foreign keys
ALTER TABLE login_tokens ADD CONSTRAINT FK_login_tokens_users_user_id
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE recipes ADD CONSTRAINT FK_recipes_users_author_id
    FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE RESTRICT;

ALTER TABLE recipes ADD CONSTRAINT FK_recipes_categories_category_id
    FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE RESTRICT;

ALTER TABLE recipes ADD CONSTRAINT FK_recipes_cuisines_cuisine_id
    FOREIGN KEY (cuisine_id) REFERENCES cuisines (cuisine_id) ON DELETE RESTRICT;

ALTER TABLE users_roles ADD CONSTRAINT FK_users_roles_users_user_id
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE users_roles ADD CONSTRAINT FK_users_roles_roles_role_id
    FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE RESTRICT;

ALTER TABLE user_favorites ADD CONSTRAINT FK_user_favorites_users_user_id
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE user_favorites ADD CONSTRAINT FK_user_favorites_recipes_recipe_id
    FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE;

ALTER TABLE recipe_ingredients ADD CONSTRAINT FK_recipe_ingredients_recipes_recipe_id
    FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE;

ALTER TABLE recipe_ingredients ADD CONSTRAINT FK_recipe_ingredients_ingredients_ingredient_id
    FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id) ON DELETE RESTRICT;

-- Unique indexes
CREATE UNIQUE INDEX IX_categories_name ON categories (name);
CREATE UNIQUE INDEX IX_cuisines_name ON cuisines (name);
CREATE UNIQUE INDEX IX_ingredients_name ON ingredients (name);
CREATE UNIQUE INDEX IX_roles_name ON roles (name);
CREATE UNIQUE INDEX IX_users_email ON users (email);

-- FK indexes
CREATE INDEX IX_login_tokens_user_id ON login_tokens (user_id);
CREATE INDEX IX_login_tokens_code_hash ON login_tokens (code_hash);
CREATE INDEX IX_login_tokens_expires_at ON login_tokens (expires_at);
CREATE INDEX IX_recipes_author_id ON recipes (author_id);
CREATE INDEX IX_recipes_category_id ON recipes (category_id);
CREATE INDEX IX_recipes_cuisine_id ON recipes (cuisine_id);
CREATE INDEX IX_users_roles_role_id ON users_roles (role_id);
CREATE INDEX IX_user_favorites_recipe_id ON user_favorites (recipe_id);
CREATE INDEX IX_recipe_ingredients_ingredient_id ON recipe_ingredients (ingredient_id);

-- Seed data (applied by migrations)
-- categories: Breakfast, Lunch, Dinner, Dessert, Salad, Drinks, Soup, Main Course (ids 1-8)
-- cuisines: Italian, English, French, Mediterranean, Spanish, Slavic (ids 1-6)
-- ingredients: Milk, Sugar, Potato, Rice, Sour cream, Salt, Egg, Pork meat, Cheese,
--              Chicken breast, Tomato, Carrot, Olive Oil, Pepperoni (ids 1-14)
-- roles: Administrator (1), User (2)
-- users are NOT seeded. Create an account via POST /api/auth/register,
-- then optionally assign the Administrator role:
--   INSERT INTO users_roles (user_id, role_id) VALUES (<user_id>, 1);
